# Site wide configuration

title:  nexocrew
locale: en_UK
url: http://nexocrew.github.io  # uncomment for live
#url: http://localhost:4000  # uncomment for dev

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
#gems:
#  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: nexocrew
  #avatar: afile.jpg
  bio: "nexocrew an organisation born in Milan."
  #email: 
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
  bing-verify: 
  github: nexocrew
  stackoverflow: #username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
